#!/bin/bash


AMBAR=~/svn/ambar/ambar.txt 

for TYPE in `head -1000 $AMBAR  | grep -v ^#| awk '{print $2}'|sort -u | grep -vE 'банк|питомец'`; 
do      i=$(($i+1))
        TYPES[$i]="$TYPE"
        #echo "=$i=$TYPE"
done

#print array
i=1
while [ $i -lt $((1+${#TYPES[@]})) ] 
do      echo "$i. ${TYPES[$i]}"
        i=$((i+1))
done |column


echo
echo "enter type:"
read i
TYPE=${TYPES[$i]}

if [ -z "$TYPE" ] 
then    echo "no type choosen"
        exit
else    echo "choosen $TYPE"
fi

DATE=`date +%F`

echo "enter sum":
read sum

echo "enter comment [optional]":
read comment

STRING=$(echo -e "$DATE\t$TYPE\t\t$sum\t$comment" )

echo "will I add the line"
echo
echo "$STRING"
echo
echo "y/n:"
read answer

if [ "$answer" == 'y' ]
then    sed -i "1i $STRING" $AMBAR
        svn diff $AMBAR
else    echo "noop"
fi


